### PR TITLE
Fix bug Heatmap (Tu-feng#16)

### PR DESCRIPTION
**Pull request by Tu-feng**
Fix bug: enable plot 0 col/row in heatmap

### CODE REVIEW

**Comment by zktuong** [comment]
ok don't worry about the job failing because of the codecov bit.

**Comment by zktuong** [comment]
thanks for this -

do you have any experience in R code? I guess I'm asking would you be able to also do a similar PR at https://github.com/zktuong/ktplots?

**Comment by zktuong** [comment]
also i think my test data in https://github.com/zktuong/ktplotspy/tree/master/data/out does contain a situation which simulates your original problem.

Perhaps can mock something up based on test like this
https://github.com/zktuong/ktplotspy/blob/9cdeedf89ad158096dbd980f939e93070aa8eb31/tests/test_plot_cpdb_heatmap.py#L27-L36

i will try and add and see if it still works

**Comment by Tu-feng** [comment]
I'm new to R, not sure if I can fix it. I will submit a PR if I can.
ktplots is a great package, thanks for your contribution and maintenance！

**Comment by zktuong** [comment]
> I'm new to R, not sure if I can fix it. I will submit a PR if I can. ktplots is a great package, thanks for your contribution and maintenance！

it would be great it you can figure it out! i just have a couple of other issues preventing me to work on them properly at the moment so i really appreciate the help.

**Pull request merged**
